name: Aprendiendo GitHub Actions
run-name : Estoy aprendiendo GitHub Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-node-version: '20'

      - name: Run inline script
        run: node -e "console.log('¡Hola desde Node.js en GitHub Actions!');"

      - name: Run external script
        run: |
          if [ -f "main.js" ]; then
            node main.js
          else
            echo "No se encontró el archivo main.js, omitiendo este paso."
          fi

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
