name: Saludo secretos
run-name: ¡Estoy aprendiendo a usar Secretos!
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-secreto:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
      run: echo "${{secrets.CONTRASENA}}"
